[library]
version = "15.1.14"
browse_url = "https://github.com/yunsiong/telco-gum/"
repository_url = "https://github.com/yunsiong/telco-gum.git"
website_url = "https://telco.re/"
authors = "Telco Development Team"
logo_url = "https://telco.re/img/logotype.svg"
license = "wxWindows"
description = "Cross-platform instrumentation and introspection library written in C."
devhelp = true
search_index = true

[source-location]
base_url = "https://github.com/yunsiong/telco-gum/blob/master/"
